-- MySQL Script generated by MySQL Workbench
-- Mon Jan  1 14:49:55 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `Empleados`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Empleados` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Empleados` (
  `idEmpleados` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `lastName` VARCHAR(45) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `phone` INT NOT NULL,
  `emergencyPhone` INT NOT NULL,
  `emergencyContact` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idEmpleados`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Gestor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Gestor` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Gestor` (
  `Gestor` INT NOT NULL,
  `Empleados_idEmpleados` INT NOT NULL,
  `Herramientas_idHerramientas` INT NOT NULL,
  `Productos_idProductos` INT NOT NULL,
  `Proyecto_idProyecto` INT NOT NULL,
  PRIMARY KEY (`Gestor`, `Empleados_idEmpleados`, `Herramientas_idHerramientas`, `Productos_idProductos`, `Proyecto_idProyecto`),
  CONSTRAINT `fk_Gestor_Empleados`
    FOREIGN KEY (`Empleados_idEmpleados`)
    REFERENCES `Empleados` (`idEmpleados`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Gestor_Herramientas1`
    FOREIGN KEY (`Herramientas_idHerramientas`)
    REFERENCES `Herramientas` (`idHerramientas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Gestor_Productos1`
    FOREIGN KEY (`Productos_idProductos`)
    REFERENCES `Productos` (`idProductos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Gestor_Proyecto1`
    FOREIGN KEY (`Proyecto_idProyecto`)
    REFERENCES `Proyecto` (`idProyecto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_Gestor_Empleados_idx` ON `Gestor` (`Empleados_idEmpleados` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `fk_Gestor_Herramientas1_idx` ON `Gestor` (`Herramientas_idHerramientas` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `fk_Gestor_Productos1_idx` ON `Gestor` (`Productos_idProductos` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `fk_Gestor_Proyecto1_idx` ON `Gestor` (`Proyecto_idProyecto` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Herramientas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Herramientas` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Herramientas` (
  `idHerramientas` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `stock` INT NOT NULL,
  `free` INT NULL,
  `busy` INT NOT NULL,
  PRIMARY KEY (`idHerramientas`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Productos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Productos` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Productos` (
  `idProductos` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `stock` INT NOT NULL,
  PRIMARY KEY (`idProductos`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Proyecto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Proyecto` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Proyecto` (
  `idProyecto` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `location` VARCHAR(45) NOT NULL,
  `Proyectocol` VARCHAR(45) NULL,
  `Empleados_idEmpleados` INT NOT NULL,
  `Productos_idProductos` INT NOT NULL,
  `Herramientas_idHerramientas` INT NOT NULL,
  PRIMARY KEY (`idProyecto`, `Empleados_idEmpleados`, `Productos_idProductos`, `Herramientas_idHerramientas`),
  CONSTRAINT `fk_Proyecto_Empleados1`
    FOREIGN KEY (`Empleados_idEmpleados`)
    REFERENCES `Empleados` (`idEmpleados`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Proyecto_Productos1`
    FOREIGN KEY (`Productos_idProductos`)
    REFERENCES `Productos` (`idProductos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Proyecto_Herramientas1`
    FOREIGN KEY (`Herramientas_idHerramientas`)
    REFERENCES `Herramientas` (`idHerramientas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_Proyecto_Empleados1_idx` ON `Proyecto` (`Empleados_idEmpleados` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `fk_Proyecto_Productos1_idx` ON `Proyecto` (`Productos_idProductos` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `fk_Proyecto_Herramientas1_idx` ON `Proyecto` (`Herramientas_idHerramientas` ASC) VISIBLE;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
